[build]
  publish = "."

[[redirects]]
  from = "https://www.tressana.ai/*"
  to = "https://tressana.ai/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
